'use client'

import { Player } from '@lottiefiles/react-lottie-player'
import Animation1 from '../assets/home_animation.json'
import Animation2 from '../assets/ticket_animation.json'
import Animation3 from '../assets/rocket_animation.json'
import Link from 'next/link'
import { Button } from './ui/button'
import { Reveal, RevealXLeft, RevealXRight, RevealWrapper } from './Reveal'

export function About() {
  return (
    <div className='w-full overflow-hidden my-16 max-w-screen-2xl'>
      {/* First */}

      <RevealWrapper>
        <div className='w-full h-96 px-[20%]'>
          <div className='flex flex-row items-center justify-between gap-6 w-full'>
            <RevealXRight delay={0.4}>
              <div className='flex flex-col space-y-6 h-full w-[450px]'>
                <p className='text-4xl font-bold text-primary'>
                  Explore your influence
                </p>
                <p>
                  With Festx, you can register to promote your favourite events
                  and parties and turn yourself into a real promoter. With just
                  a few clicks and completely for free.
                </p>
                <Link href='/createProfile' passHref>
                  <Button variant='outline'>Get Started Now</Button>
                </Link>
              </div>
            </RevealXRight>
            <Reveal delay={0.6}>
              <div className='h-96'>
                <Player
                  src={Animation1}
                  className='player h-96'
                  loop
                  autoplay
                />
              </div>
            </Reveal>
          </div>
        </div>
      </RevealWrapper>

      {/* Second */}

      <RevealWrapper>
        <div className='w-full h-96 px-[20%]'>
          <div className='flex flex-row items-center justify-between gap-6'>
            <Reveal delay={0.6}>
              <div className='h-96'>
                <Player
                  src={Animation2}
                  className='player h-96'
                  loop
                  autoplay
                />
              </div>
            </Reveal>
            <RevealXLeft delay={0.4}>
              <div className='flex flex-col space-y-6 h-full w-[450px]'>
                <p className='text-4xl font-bold text-primary'>Get rewards</p>
                <p>
                  With your code generated by Festx, share with your friends and
                  earn tokens for other events. As more people you can bring,
                  more you earn!
                </p>
                <Link href='/rewards' passHref>
                  <Button variant='outline'>See our Rewards</Button>
                </Link>
              </div>
            </RevealXLeft>
          </div>
        </div>
      </RevealWrapper>

      {/* Third */}

      <RevealWrapper>
        <div className='w-full h-96 px-[20%]'>
          <div className='flex flex-row items-center justify-between gap-6'>
            <RevealXRight delay={0.4}>
              <div className='flex flex-col space-y-6 h-full w-[450px]'>
                <p className='text-4xl font-bold text-primary'>
                  Skyrocket your networking
                </p>
                <p>
                  Connect with people from all spheres of events, embrace
                  diversity! With Festx, you can promote whatever kind of event
                  you want.
                </p>
                <Link href='/campaigns' passHref>
                  <Button variant='outline'>Promote a Campaign</Button>
                </Link>
              </div>
            </RevealXRight>
            <Reveal delay={0.6}>
              <div className='h-96'>
                <Player
                  src={Animation3}
                  className='player h-96'
                  loop
                  autoplay
                />
              </div>
            </Reveal>
          </div>
        </div>
      </RevealWrapper>
    </div>
  )
}
