import bkg from '@/assets/cia_BKG.png'
import avatar from '@/assets/cia_BKG.png'

export const userData = [
  {
    id: 1,
    name: 'Bry',
    email: 'brybry@gmail.com',
    instagram: 'brybry',
    password: '123456',
    avatar: avatar,
    balance: 1000,
    code: 'BRY24',
    location: 'São José dos Campos',
    pix: 'brybry@gmail.com',
    campaigns: [1, 2, 3, 4],
    tickets: [1, 3],
  },
]

export const eventData = [
  {
    id: 1,
    name: 'CIA',
    description: 'random',
    image: bkg,
    location: 'Uberaba - MG',
    instagram: 'cia',
    date: '30/05/2024',
    category: 'Festival',
    tokenSupply: '1000',
    tokenEarned: '100',
    tokenSpent: '200',
    price: '100',
  },
  {
    id: 2,
    name: 'Tusca',
    description: 'random',
    image: bkg,
    location: 'São Carlos - SP',
    instagram: 'tusca',
    date: '30/10/2024',
    category: 'Festival',
    tokenSupply: '1000',
    tokenEarned: '100',
    tokenSpent: '200',
    price: '100',
  },
  {
    id: 3,
    name: 'Event 3',
    description: 'random',
    image: bkg,
    location: 'Uberaba',
    instagram: 'event',
    date: '30/05/2024',
    category: 'Festival',
    tokenSupply: '1000',
    tokenEarned: '100',
    tokenSpent: '200',
    price: '100',
  },
  {
    id: 4,
    name: 'Event 4',
    description: 'random',
    image: bkg,
    location: 'Uberaba',
    instagram: 'event',
    date: '30/05/2024',
    category: 'Festival',
    tokenSupply: '1000',
    tokenEarned: '100',
    tokenSpent: '200',
    price: '100',
  },
]
